version: 2.1

jobs:
  build_kernel:
    docker:
      - image: ubuntu:22.04  # Menggunakan Ubuntu 22.04
    resource_class: large
    steps:
      - checkout  # Clone repo kernel
      - run:
          name: Install Dependencies
          command: |
            apt update && apt install -y bc bison flex build-essential \
              git python3 libssl-dev libncurses5-dev \
              crossbuild-essential-arm64 libelf-dev curl
      - run:
          name: Setup KernelSU Next
          command: |
            cd kernel_xiaomi_lavender  # Ganti dengan folder kernel yang sesuai
            curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next-susfs/kernel/setup.sh" | bash -s next-susfs
      - run:
          name: Build Kernel
          command: |
            cd kernel_xiaomi_lavender
            make ARCH=arm64 O=out defconfig
            make ARCH=arm64 O=out -j$(nproc)
      - store_artifacts:
          path: kernel_xiaomi_lavender/out/arch/arm64/boot/Image.gz-dtb
          destination: Image.gz-dtb

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_kernel